### ISSUE TITLE
Subset Returns 1d Array

### ISSUE THREAD

**Issue by HumphreysCarter** [jswhit/pygrib#179]
Hello,

I'm trying to subset the HRRR to a more local domain but it returns a 1d array when I use `grb.data()` which then doesn't work with matplotlib, how can I get a 2d array? 

```
grbs = pygrib.open('hrrr.t06z.wrfprsf12.grib2')

grb = grbs.select(name='Derived radar reflectivity', typeOfLevel='heightAboveGround', level=1000)[0]

data, lats, lons = grb.data(lat1=41.5, lat2=45.5, lon1=-80.5, lon2=-72.5)
print(data.shape, lats.min(), lats.max(), lons.min(), lons.max())
````
Output:
```
(32146,) 41.500284998538184 45.49993105177101 -80.49977556935403 -72.50033808325453
```

**Comment by jswhit** [comment]
from the docs "If the grid type is unprojected lat/lon and a geographic subset is requested (by using the lat1,lat2,lon1,lon2 keywords), then 2-d arrays are returned, otherwise 1-d arrays are returned"  

In other words, you only get a 2-d array if the grid is lat/lon.  In your case, it's lambert conformal so you get a 1-d array containing all the points in the selected region.

Why not plot the entire array and zoom in on that region with matplotlib/cartopy?

**Comment by HumphreysCarter** [comment]
That was working, but I figured subsetting it to a more local domain would be more efficient? I thought in the past I was able to do that, maybe that was an unprojected dataset.

**Comment by jswhit** [comment]
there's no way I know of to return a 2d array given lat/lon corners unless the grid is lat/lon.  T
